export 'package:flutter/material.dart';
export 'package:sem_5/sem5lab/lab_2/lab2_5/amazon_controller.dart';
export 'package:sem_5/sem5lab/lab_2/lab2_5/amazon_model.dart';
export 'package:sem_5/sem5lab/lab_2/lab2_5/amazon_view.dart';
export 'dart:async';
export 'package:sem_5/sem5lab/lab_2/lab2_1/favorite_controller.dart';
export 'package:sem_5/sem5lab/lab_2/lab2_1/favorite_model.dart';
export 'package:sem_5/sem5lab/lab_2/lab2_1/favorite_view.dart';
export 'package:sem_5/sem5lab/lab_2/lab2_4/profile_card_controller.dart';
export 'package:sem_5/sem5lab/lab_2/lab2_4/profile_card_model.dart';
export 'package:sem_5/sem5lab/lab_2/lab2_2/signup_controller.dart';
export 'package:sem_5/sem5lab/lab_2/lab2_2/signup_model.dart';
export 'package:sem_5/sem5lab/lab_2/lab2_2/signup_view.dart';
export 'package:carousel_slider/carousel_slider.dart';
export 'package:flutter_svg/svg.dart';
export 'package:sem_5/sem5lab/lab_3/crud_list_controller.dart';
export 'package:sem_5/sem5lab/lab_3/crud_list_model.dart';
export 'package:sem_5/sem5lab/lab_3/crud_list_view.dart';
export 'package:sqflite/sqflite.dart';
export 'package:path/path.dart';
export 'package:get/get_core/src/get_main.dart';
export 'package:sem_5/sem5lab/lab_4/lab_4_1.dart';
export 'package:sem_5/sem5lab/lab_4/lab_4_2.dart';
export 'package:sem_5/sem5lab/lab_4/lab_4_3.dart';
export 'package:get/get.dart';
export 'package:sem_5/sem5lab/lab_5/lab5_1.dart';
export 'package:sem_5/sem5lab/lab_5/lab5_1_2.dart';
export 'package:sem_5/sem5lab/lab_5/lab5_2_1.dart';
export 'package:sem_5/sem5lab/lab_5/lab5_2_2.dart';
export 'dart:math';
export 'package:sem_5/sem5lab/lab_7/lab7_1.dart';
// export 'package:home1/sem5lab/lab_7/lab7_1_controller.dart';
export 'package:sem_5/sem5lab/lab_7/lab7_2_controller.dart'; 
export 'package:sem_5/sem5lab/lab_7/lab7_2.dart';
export 'package:sem_5/sem5lab/lab_5/lab5_5_hi-page.dart';
export 'package:sem_5/sem5lab/lab_5/lab5_5_bye-page.dart';
export 'package:sem_5/sem5lab/lab_5/lab5_5_middleware.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_1/getx_view.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_1/getx_controller.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_1/getx_model.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_2/rx_variable_controller.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_2/rx_variable_model.dart';
// export 'package:sem_5/sem5lab/lab_6/lab6_2/rx_variable_view.dart;
export 'package:sem_5/sem5lab/lab_6/lab6_3/rx_str_controller.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_3/rx_str_model.dart';
// export 'package:sem_5/sem5lab/lab_6/lab6_3/rx_str_view.dart'; 
export 'package:sem_5/sem5lab/lab_6/lab6_4/rx_int_view.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_4/rx_int_model.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_4/rx_int_controller.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_5/rx_bool_model.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_5/rx_bool_controller.dart';
export 'package:sem_5/sem5lab/lab_6/lab6_5/rx_bool_view.dart';
export 'package:sem_5/sem5lab/lab_7/lab7_4/crud_rxlist_controller.dart';
export 'package:sem_5/sem5lab/lab_7/lab7_4/crud_rxlist_model.dart';
// export 'package:sem_5/sem5lab/lab_7/lab7_4/crud_rxlist_view.dart';

